### ISSUE TITLE
Binary w/o popcnt requested

### ISSUE THREAD

**Issue by rwbc** [sovaz1997/Zevra#2]
Binary w/o popcnt requested for testing.

**Comment by sovaz1997** [comment]
In the next release I compile for the two options (with popcnt and without popcnt). Do you speak Russian?

**Comment by rwbc** [comment]
Hello Oleg,

Thanks! Sorry, I only speak German/English and a bit French.

Best regards,
Guenther

On 7 Nov 2016 at 7:24, sovaz1997 wrote:

> In the next release I compile for the two options (with popcnt and
> without popcnt). Do you speak 
> Russian?
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the
> thread.

---

Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by sovaz1997** [comment]
Thank you! The new version of I'll post either today or tomorrow, do not know yet.

**Comment by sovaz1997** [comment]
I, unfortunately, do not have processors without popcnt. But you can check out the new version. If you will be working, email me.

**Comment by rwbc** [comment]
The new version works on a machine w/o popcnt. Thanks.
There is a problem though with the thinking output. You should suppress output for low depths
and even more important lines with currmove currmovenumber will not be displayed.
E.g. in polyglot no thinking output will be shown at all. The last info will be saved to pgn.

**Comment by sovaz1997** [comment]
In the new version I improve the output of the program and (probably) will implement the output variation pv.
