### ISSUE TITLE
Missing dll-files to run Zevra 2.17 on Windows 7 SP1 x64 OS

### ISSUE THREAD

**Issue by ChessGUI** [sovaz1997/Zevra#5]
Hello sovaz1997, 

can you please contact the author of RWBC http://www.rwbc-chess.de/  in Germany, please?

Is Zebra 2.17 an official edition and the direct successor of v1.0? The source code was obviously changed, but it is not mentioned on https://github.com/sovaz1997/Zevra/releases or http://www.sdchess.ru/download_engines.htm .
To execute your engine on Arena GUI http://www.playwitharena.com/, two missing dll-files are required:
libgcc_s_seh-1.dll ~ http://www.dll-found.com/download/l/libgcc_s_seh-1.dll
libstdc++-6.dll 64 bit ~  https://qemu.weilnetz.de/w64/dll/libstdc++-6.dll

If you use the wrong 32-bit version cf. https://de.dll-files.com/libstdc++-6.dll.html an error indication appears like this: : application cannot be launched correctly (0xc000007b) - click on "ok" to close the program.

**Comment by sovaz1997** [comment]
This is 217 commit (non oficial), the official version is version v1.0. In the near future I will release a new version, based on the latest сommit. Then I'll write here: http://www.rwbc-chess.de/.
